#!/usr/bin/env bash

set -e

#  ____       _       _     _
# | __ ) _ __(_) __ _| |__ | |_ _ __   ___  ___ ___
# |  _ \| '__| |/ _` | '_ \| __| '_ \ / _ \/ __/ __|
# | |_) | |  | | (_| | | | | |_| | | |  __/\__ \__ \
# |____/|_|  |_|\__, |_| |_|\__|_| |_|\___||___/___/
#               |___/

declare -A icons
path="$HOME/.scripts/icons"
icons[off]="$path/brightness-off.svg"
icons[low]="$path/brightness-low.svg"
icons[medium]="$path/brightness-medium.svg"
icons[high]="$path/brightness-high.svg"

dependencies() {
	dependencies=(light)
	for cmd in "${dependencies[@]}"; do
		command -v "$cmd" >/dev/null && continue || {
			echo "$cmd command not found."
			exit 1
		}
	done
}

get_notification_icon() {
	current=$(light -G)
	brightness=${current%.*}
	if [ "$brightness" -lt "30" ]; then
		echo "${icons[low]}"
	elif [ "$brightness" -lt "60" ]; then
		echo "${icons[medium]}"
	elif [ "$brightness" -lt "100" ]; then
		echo "${icons[high]}"
	elif [ "$brightness" -eq "100" ]; then
		echo "${icons[high]}"
	fi
}

send_notification() {
	icon=$(get_notification_icon)
	current=$(light -G)
	brightness=${current%.*}
	options="string:x-canonical-private-synchronous:brightness"
	dunstify -a "Brightness" "Brightness" "Brightness" -i "$icon" -h int:value:"$brightness" -h $options
}

status_bar() {
	low=""
	mid=""
	high=""
	current=$(light -G)
	brightness=${current%.*}

	printf "%s" "$SEP1"
	if [ "$brightness" -lt "30" ]; then
		icon="$low"
	elif [ "$brightness" -lt "60" ]; then
		icon="$mid"
	elif [ "$brightness" -lt "100" ]; then
		icon="$high"
	elif [ "$brightness" -eq "100" ]; then
		icon="$high"
	fi
	printf "%s %s" "$icon" "$brightness%"
	printf "%s" "$SEP2"
}

increase() {
	light -A "$1"
}

decrease() {
	light -U "$1"
}

usage() {
	program=$(basename "$0")
	echo "$program [OPTIONS] [VALUE]"
	echo
	echo "Simple script for managing brightness"
	echo
	echo "Usage: $program <increase|decrease>"
	echo
	echo "options:"
	echo " inc		Increase brightness by 5%."
	echo " dec		Decrease brightness by 5%."
	echo " -h		Print this Help."
	echo
	exit 0
}

main() {
	dependencies

	case "$1" in
	inc) increase "${2:-5}" ;;
	dec) decrease "${2:-5}" ;;
	status) status_bar ;;
	*) usage ;;
	esac

	send_notification
}

main "$1" "$2"
