#!/usr/bin/env bash

# script to hibernate/suspend with `zzz/ZZZ`
#
# this script monitors specific lock files to manage system hibernation and
# suspension.
# it runs continuously in the background, checking for the presence of lock
# files to determine whether to trigger hibernation.
# dependency: 'suspend-hybrid' script

PROG="${0##*/}"
LOGGER="${LOGS_PATH:-$HOME/dcs/log}/suspend-hibernate.log"
DEPS=(zzz ZZZ tee)

# lock files
LOCKS=$HOME
HIBERNATE_LOCK="$LOCKS/hibernate.lock"
WAKEUP_LOCK="$LOCKS/wakeup.lock"
SLEEP=5s

# logs messages with timestamps and script name to the log file.
function logger {
    local now
    if [[ ! -f "$LOGGER" ]]; then
        create_file "$LOGGER"
    fi

    now=$(date '+%F %T')
    echo "[${now}]::[$PROG]::$1" | tee -a "$LOGGER"
}

function send_notification {
    local prog
    local mesg="<b>$1</b>"
    prog=$(echo "$PROG" | tr '[:lower:]' '[:upper:]')
    notify-send -r 938 -i dialog-warning "$prog" "$mesg"
}

# prints a separator line in the log file.
function line {
    local w="79"
    local char="-"
    printf "%${w}s\n" | sed "s/ /$char/g"
}

# adds a separator line to the log file.
function separator {
    line | tee -a "$LOGGER"
}

# checks if one of the lockers are seen.
function seen {
    local trigger="$1"
    if [[ ! -f "$trigger" ]]; then
        return 1
    fi

    logger "found $trigger"
    return 0
}

# checks if the manual lock file exists.
function is_manual_hibernate {
    if [[ ! -f "$MANUAL_LOCK" ]]; then
        return 1
    fi

    logger "found $MANUAL_LOCK"
    return 0
}

# removes a specified lock file and logs the action.
function remove_lock {
    local file="$1"

    if [[ ! -f "$file" ]]; then
        return
    fi

    logger "removing $file"
    rm -f "$file"
    sleep 0.5
}

# creates a specified file and logs the action.
function create_file {
    local file="$1"
    touch "$file"
    logger "creating $file"
    sleep 0.5
}

# checks if the automatic hibernate lock file exists.
function is_ready_to_hibernate {
    if [[ ! -f "$HIBERNATE_LOCK" ]]; then
        return 1
    fi

    logger "found $HIBERNATE_LOCK"
    return 0
}

# creates a wakeup lock file and triggers the hibernation process
# using sudo ZZZ.
function suspend_hybrid {
    logger "setting up to after wake-up"
    create_file "$WAKEUP_LOCK"

    logger "entering hibernate-mode...sudo ZZZ"
    separator
    sudo ZZZ
}

function pre_exit {
    remove_lock "$LOGGER"
}

for dep in "${DEPS[@]}"; do
    if ! command -v "$dep" &>/dev/null; then
        logger "missing dependency: $dep"
        exit 1
    fi
done

logger "started at $(date)"

trap pre_exit EXIT SIGTERM

while true; do
    if seen "$HIBERNATE_LOCK"; then
        remove_lock "$HIBERNATE_LOCK"
        suspend_hybrid
    fi

    sleep "$SLEEP"
done
