#!/usr/bin/env bash

# ╻  ┏━┓┏━╸╻┏ ┏━╸┏━┓
# ┃  ┃ ┃┃  ┣┻┓┣╸ ┣┳┛
# ┗━╸┗━┛┗━╸╹ ╹┗━╸╹┗╸
# simple locker with xautolock and zzz

PROG=$(basename "$0")
DEPS=(xautolock zzz setsid)
SUSPEND_TIME=30
LOCKER="sudo zzz"
CMD="xautolock"

function log_err {
    printf "%s: %s\n" "$PROG" "$*"
    exit 1
}

function is_running {
    if ! pgrep -x "$CMD" >/dev/null; then
        return 1
    fi
    return 0
}

function kill_locker {
    pkill -x "$CMD"
}

function usage {
    cat <<-END
[0;1;34;94m╻[0m  [0;1;34;94m┏━┓┏━╸╻┏[0m [0;1;34;94m┏━╸┏[0;34m━┓[0m
[0;1;34;94m┃[0m  [0;1;34;94m┃[0m [0;1;34;94m┃┃[0m  [0;34m┣┻┓┣╸[0m [0;34m┣┳┛[0m
[0;34m┗━╸┗━┛┗━╸╹[0m [0;34m╹┗━╸╹[0;37m┗╸[0m

simple locker with xautolock and zzz

Usage: $PROG <timer in minutes> (default: 30m)
END
}

function main {
    local timer dep
    timer="$1"

    for dep in "${DEPS[@]}"; do
        if ! command -v "$dep" >/dev/null; then
            log_err "'$dep' not found"
        fi
    done

    if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
        usage
        exit
    fi

    if is_running; then
        kill_locker
    fi

    [[ -n "$timer" ]] && SUSPEND_TIME=$timer
    setsid -f "$CMD" -time "$SUSPEND_TIME" -locker "$LOCKER" -detectsleep
}

main "$@"
