#!/usr/bin/env bash

# ╻  ┏━┓┏━╸┏━┓
# ┃  ┃ ┃┃╺┓┗━┓
# ┗━╸┗━┛┗━┛┗━┛
# view/edit logs

set -o nounset
set -o pipefail

PROG=$(basename "$0")
LOGS_PATH=${LOGS_PATH:-$HOME/dcs/log}
TERMINAL=${TERMINAL:-st}
LOGS_FILES=("$LOGS_PATH"/*)
PROMPT="${PROG}> "

declare -a LOGS_NAMES
for log in "${LOGS_FILES[@]}"; do
    name=$(basename "${log}")
    LOGS_NAMES+=("${name}")
done

# if not on a terminal, use dmenu
if [[ ! -t 1 ]]; then
    log=$(printf '%s\n' "${LOGS_NAMES[@]}" | dmenu -l 10 -p "$PROMPT")
    [[ -n "${log}" ]] && $TERMINAL -n splogs -c splogs -g 120x30 -e nvim "${LOGS_PATH}/${log}"
else
    log=$(printf '%s\n' "${LOGS_NAMES[@]}" | fzf --tmux "center,50%" --no-preview --prompt="$PROMPT")
    [[ -n "${log}" ]] && "${EDITOR:-nvim}" "${LOGS_PATH}/${log}"
fi
