#!/usr/bin/env bash

# ┏┳┓┏━┓╻╻  ╺┳╸┏━┓
# ┃┃┃┣━┫┃┃   ┃ ┃ ┃
# ╹ ╹╹ ╹╹┗━╸ ╹ ┗━┛
#
# script to launch an email client (neomutt) with the selected account
# configuration.

PROG=$(basename "$0")
SHELL=${SHELL:-$(which zsh)}
TERMINAL=${TERMINAL:-st}
MUTT="${XDG_CONFIG_HOME:-$HOME/.config}/mutt"
declare -a ACCOUNTS

# colors
BLUE="#5f819d"
WHITE="#f8f8f2"

# menu
MENU="dmenu"
declare -a MENU_ARGS=(-i -l 10)

function usage {
    echo "usage: $PROG <email>"
}

function logerr_exit {
    printf "%s: %s\n" "$PROG" "$*" >&2
    exit 1
}

function accounts_load {
    local path files
    path="$MUTT/accounts"
    files=$(cd "$path" && find . | tail -n +2 | sed "s/\.\///g; s/\.muttrc$//g")

    [[ -z "$files" ]] && logerr_exit "no accounts found in $path"

    IFS=$'\n' readarray -t ACCOUNTS <<<"$files"
}

function accounts_getfile {
    local choice="$1"
    local account_name
    account_name=$(find "$MUTT/accounts" -name "*$choice*")

    echo "$account_name"
}

function account_select {
    local choice
    MENU_ARGS+=(-p " Sender>")
    MENU_ARGS+=(-sb "$BLUE" -sf "$WHITE")
    choice=$(printf "%s\n" "${ACCOUNTS[@]}" | "$MENU" "${MENU_ARGS[@]}")

    echo "$choice"
}

function run_email_client {
    local account_file account_name send_to
    account_name="$1"
    send_to="$2"
    account_file=$(accounts_getfile "$account_name")

    [[ -z "$account_file" ]] && logerr_exit "account '$account_name' not found"

    setsid -f "$TERMINAL" -e neomutt "$send_to" -F "$MUTT/muttrc" -F "$account_file"
}

function dependencies {
    declare -a deps=(neomutt setsid dmenu)
    for dep in "${deps[@]}"; do
        if ! command -v "$dep" >/dev/null; then
            logerr_exit "'$dep' not found"
        fi
    done

}

function main {
    dependencies

    local sendto="$1"
    local account_path=$MUTT/accounts
    if [[ ! -d "$account_path" ]]; then
        logerr_exit "no mutt accounts found in $account_path"
    fi

    [[ -z "$sendto" ]] && {
        usage
        exit 1
    }

    accounts_load

    if [[ "${#ACCOUNTS[@]}" -eq 1 ]]; then
        run_email_client "${ACCOUNTS[@]}" "$sendto"
        return 0
    fi

    local account_chose
    account_chose=$(account_select)
    [[ -z "$account_chose" ]] && logerr_exit "no account selected"

    run_email_client "$account_chose" "$sendto"
}

main "$@"
