#!/usr/bin/env bash

# Simple script for screenshot
# - Pretty mode (add shadow, corner radious, white backdrop)
# - Normal mode
#
# https://github.com/flameshot-org/flameshot

PROG=$(basename "$0")
DEPENDENCIES=(flameshot convert dunstify nsxiv)
LOCATION="${XDG_DOWNLOAD_DIR:-$HOME/downloads}"/screenshots
IMAGE_TMP=$(mktemp --tmpdir "$PROG.XXXXX")

function log_err() {
	printf "%s: %s\n" "$PROG" "$*" >&2
	exit 1
}

function notify() {
	local mesg="$1"
	dunstify -i flameshot "$PROG" "$mesg"
}

function open() {
	local image width height
	image="$1"

	[[ ! -f "${image}" ]] && log_err "'${image}' not found"

	width=$(identify -format "%w" "$image") >/dev/null
	height=$(identify -format "%h" "$image") >/dev/null
	nsxiv --geometry="${width}x${height}" "${image}" 2>/dev/null
}

function pretty() {
	local filesize dest
	flameshot gui --raw >"$IMAGE_TMP" 2>/dev/null

	filesize=$(stat -c%s "$IMAGE_TMP")
	if [[ "$filesize" -le 0 ]]; then
		echo "$PROG: aborting..."
		exit 1
	fi

	# add corners
	convert "$IMAGE_TMP" \
		\( +clone -alpha extract \
		-draw 'fill black polygon 0,0 0,15 15,0 fill white circle 15,15 15,0' \
		\( +clone -flip \) -compose Multiply -composite \
		\( +clone -flop \) -compose Multiply -composite \
		\) -alpha off -compose CopyOpacity -composite "$IMAGE_TMP"

	# shadow
	convert "$IMAGE_TMP" \
		\( +clone -background black -shadow 40x5+0+0 \) \
		+swap -background none -layers merge +repage "$IMAGE_TMP"

	# white backdrop
	convert "$IMAGE_TMP" -bordercolor white -border 10 "$IMAGE_TMP"

	# copy to clipboard
	xclip -selection clipboard -i "$IMAGE_TMP" -t image/png
	dest="${LOCATION}/pretty-$(date +%Y-%m-%d_%H:%M:%S).png"

	cp -v "$IMAGE_TMP" "${dest}"
	notify "Screenshot saved at <b>${LOCATION}</b>"
	open "${dest}"
}

function normal() {
	flameshot gui --clipboard 2>/dev/null
}

function help() {
	cat <<-_EOF
		Usage: $PROG [options]

		options:
		  -p, --pretty      Add shadow, round corners and white backdrop
		  -n, --normal      Normal screenshot with flameshot GUI
		  -d, --destop      Desktop screenshot
		  -h, --help        Show this help
	_EOF
	exit
}

for cmd in "${DEPENDENCIES[@]}"; do
	if ! command -v "$cmd" >/dev/null; then
		log_err "'$cmd' command not found"
	fi
done

case "$1" in
-n | *normal) normal ;;
-p | *pretty) pretty ;;
-d | *desktop | *full) flameshot full -c -p "${LOCATION}" ;;
*) help ;;
esac
