#!/usr/bin/env bash

# ┏━╸╻╻  ┏━╸┏━┓
# ┣╸ ┃┃  ┣╸ ┗━┓
# ╹  ╹┗━╸┗━╸┗━┛
# simple file-selector and share with dragon-drop
# deps: <nnn> <dragon-drop>

set -o nounset
set -o errexit
set -o pipefail

PROG="${0##*/}"
TMPFILE="$(mktemp -t "$PROG.XXXXXX")"
DEPS=(nnn dragon-drop)

# shellcheck source=/dev/null
[[ -f "$HOME/.config/shell/nnn.sh" ]] && . "$HOME/.config/shell/nnn.sh"

function _notifyme {
    local prog
    local mesg="<b>$1</b>"
    prog=$(echo "$PROG" | tr '[:lower:]' '[:upper:]')
    notify-send -i "gnome-user-share" "$prog" "$mesg"
}

function _logerr {
    local msg="$1"
    _notifyme "$msg"
    printf "%s: %s\n" "$PROG" "$msg" >&2
    exit 1
}

function pre_exit {
    if [[ ! -f "$TMPFILE" ]]; then
        return
    fi
    rm "$TMPFILE" 2>/dev/null
}

function _has {
    local verbose=false
    local c
    if [[ $1 == '-v' ]]; then
        verbose=true
        shift
    fi
    for c in "$@"; do
        c="${c%% *}"
        if ! command -v "$c" &>/dev/null; then
            [[ "$verbose" == true ]] && _logerr "'$c' not found"
            return 1
        fi
    done
}

trap pre_exit EXIT SIGTERM

_has -v "${DEPS[@]}"

if [[ -n "${1:-}" ]]; then
    setsid -f dragon-drop -x "$1"
    exit 0
fi

nnn -p "$TMPFILE"

if [[ -f "$TMPFILE" ]]; then
    setsid -f dragon-drop --and-exit --stdin --on-top <"$TMPFILE"
fi
