#!/usr/bin/env bash

# ┏━┓╻ ╻┏━┓┏━┓┏━╸┏┓╻╺┳┓
# ┗━┓┃ ┃┗━┓┣━┛┣╸ ┃┗┫ ┃┃
# ┗━┛┗━┛┗━┛╹  ┗━╸╹ ╹╺┻┛
# script to hibernate/suspend with `zzz/ZZZ`
#
# this script sets timers and lock files.
# dependency: 'hibernate-loop' script

PROG="${0##*/}"
CURRENT_TIME=$(date +%s)
LOGGER="${LOGS_PATH:-$HOME/dcs/log}/suspend-hibernate.log"

# AC offline in minutes
HIBERNATE_DELAY=60
# AC online in minutes
HIBERNATE_DELAY_CHAR=90

# lock files
LOCKS=$HOME
SUSPEND_LOCK="$LOCKS"/suspend.lock
HIBERNATE_LOCK="$LOCKS/hibernate.lock"
WAKEUP_LOCK="$LOCKS/wakeup.lock"
TIMER="/tmp/timer.log"

function usage {
    echo "Usage: $PROG [suspend|resume]"
    exit 1
}

function _logger {
    local now
    if [[ ! -f "$LOGGER" ]]; then
        touch "$LOGGER"
    fi

    now=$(date '+%F %T')
    echo "[${now}]::[$PROG]::$1" | tee -a "$LOGGER"
}

function _line {
    local w char
    w="79"
    char="-"
    printf "%${w}s\n" | sed "s/ /$char/g"
}

function _file_touch {
    local file="$1"
    touch "$file"
    _logger "creating $file"
    sleep 1
}

function _file_remove {
    local file="$1"
    if [[ ! -f "$file" ]]; then
        return
    fi

    rm -f "$file" && _logger "removing $file"
    sleep 0.5
}

function _set_timer {
    local time
    time="$1"
    _logger "setting a wake-up timer for $time min"
    # [mode: no] Don’t suspend, only set the RTC wakeup time.
    sudo rtcwake --mode no --date "+${time}min"
    _logto "$((time * 60))" "$TIMER"
}

function _disable_timer {
    _logger "disabling the wake-up timer"
    sudo rtcwake --mode disable
}

function _battery_status {
    local bat_status bat_charge
    bat_charge=$(cat /sys/class/power_supply/BAT0/capacity)
    bat_status=$(cat /sys/class/power_supply/BAT0/status)

    echo "$bat_status::${bat_charge}%"
}

function _is_hibernate_mode {
    if [[ ! -f "$WAKEUP_LOCK" ]]; then
        return 1
    fi

    return 0
}

function _is_ac_online {
    # /sys/class/power_supply/AC/online
    # online == 1 | offline == 0
    local status
    status=$(cat /sys/class/power_supply/AC/online)
    if [[ "$status" = "0" ]]; then
        return 1
    fi

    return 0
}

function _quit {
    local code="$1"
    _line | tee -a "$LOGGER"
    exit "$code"
}

function _title {
    local mode
    mode=$(echo "$1" | tr '[:lower:]' '[:upper:]')
    _logger "::::::::::::MODE $mode:::::::::::::"
}

function _logto {
    local data="$1"
    local file="$2"
    echo "$data" >"$file"
}

function _mode_manual_hibernate {
    _file_touch "$HIBERNATE_LOCK"
    _logger "setting for manual hibernate..."
    _quit 0
}

function _mode_suspend {
    if _is_hibernate_mode; then
        _logger "$WAKEUP_LOCK exists"
        _logger "hibernating..."
        _quit 0
    fi

    if _is_ac_online; then
        _logger "AC is online, update timer to $HIBERNATE_DELAY_CHAR min"
        HIBERNATE_DELAY=$HIBERNATE_DELAY_CHAR
    fi

    _logto "$CURRENT_TIME" "$SUSPEND_LOCK"
    _set_timer "$HIBERNATE_DELAY"
    _logger "entering suspend-mode..."
}

function _mode_resume {
    # Woke up from hibernate
    if _is_hibernate_mode; then
        _file_remove "$WAKEUP_LOCK"
        _logger "waking up from hibernate-mode...yawn"
        _quit 0
    fi

    # Woke up from suspend
    suspend_time=$(cat "$SUSPEND_LOCK")
    timediff=$((CURRENT_TIME - suspend_time))
    hibernate_delay=$(cat "$TIMER")
    _file_remove "$TIMER"
    _logger "timediff = $timediff"
    _logger "hibernate delay $hibernate_delay seconds"

    # Woke up from timer
    if [[ "$timediff" -ge "$hibernate_delay" ]]; then
        _logger "waking up from timer"
        _logger "setting up for hibernate-mode"
        _file_remove "$SUSPEND_LOCK"
        _file_touch "$HIBERNATE_LOCK"
        exit 0
    fi

    # Woke up by user activity
    _logger "waking up by user activity"
    _logger "system suspended for $((timediff / 60)) min"
    _file_remove "$SUSPEND_LOCK"
    _disable_timer
    _logger "waking up from suspend-mode...yawn"
}

function main {
    local mode="$1"

    if [[ ! "$mode" =~ ^(suspend|resume|manual)$ ]]; then
        usage
    fi

    _title "$mode"
    _logger "battery::$(_battery_status)"

    case "$mode" in
    suspend) _mode_suspend ;;
    resume) _mode_resume ;;
    manual) _mode_manual_hibernate ;;
    *) usage ;;
    esac

    _quit 0
}

main "$@"
