#!/usr/bin/env bash

# Extracts the <YouTube Channel ID> from a given <URL>
# Extracts <channel_id> from <url> https://www.youtube.com/@username

PROG=$(basename "$0")
DEPS=(curl grep)

usage() {
	cat <<-_EOF
		usage: $PROG <URL>

		example:
		  https://www.youtube.com/@username
	_EOF
	exit 0
}

err_and_exit() {
	printf "%s: %s\n" "$PROG" "$@"
	exit 1
}

for dep in "${DEPS[@]}"; do
	if ! command -v "$dep" >/dev/null; then
		err_and_exit "cmd '$dep' not found"
	fi
done

if [[ "$#" -ne 1 ]]; then
	usage
fi

url="$1"
[[ -z "$url" ]] && err_and_exit "no <URL> found"

channel_id=$(curl -sL "$url" | grep -oP 'href="https://www\.youtube\.com/feeds/videos\.xml\?channel_id=\K[^"]+')

if [[ -z "$channel_id" ]]; then
	err_and_exit "no <Channel ID> found in the provided <URL>"
fi

channel_url="https://www.youtube.com/feeds/videos.xml?channel_id=${channel_id}"
echo "$channel_url" | xclip -selection clipboard
echo "$channel_url"
