#!/usr/bin/env bash

# Script for displaying battery status in dwm bar.
#
# Output: [UNICODE 98%]
# Output: [UNICODE 98% status]

BAT_CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
CRITICAL=10

# notification icons
warn="🔴"
icon_critical=""
icon_empty=""
icon_low=""
icon_mid=""
icon_full=""
icon_char=""

function send_notification {
    local args
    local cmd=notify-send
    declare -a args=(-a "Battery" "Battery" "Battery critical: ")
    args+=(-r 999 --urgency=critical)
    args+=(-i "battery-level-10-symbolic")
    args+=(-h int:value:"$BAT_CHARGE")
    args+=(-h string:x-canonical-private-synchronous:battery)
    "$cmd" "${args[@]}"
}

function status {
    local current
    current=$(cat /sys/class/power_supply/BAT0/status)
    echo "$current"
}

function is_charching {
    if [[ $(status) != "Charging" ]]; then
        return 1
    fi
    return 0
}

function get_charging_bar {
    # Output: [  50%]
    #  
    # ▓ ▒ ░
    local icon=""
    local charge_level
    charge_level=$((BAT_CHARGE / 10))

    for i in $(seq 2 9); do
        if [[ $i -le $charge_level ]]; then
            icon+=""
        else
            icon+=""
        fi
    done

    if [[ $charge_level -ge 10 ]]; then
        icon+=""
    else
        icon+=""
    fi

    echo "$icon"
}

function get_icon {
    local icon=""
    if [[ "$BAT_CHARGE" -lt "20" ]]; then
        icon="$warn $icon_critical"
    elif [[ "$BAT_CHARGE" -lt "30" ]]; then
        icon="$icon_empty"
    elif [[ "$BAT_CHARGE" -lt "50" ]]; then
        icon="$icon_low"
    elif [[ "$BAT_CHARGE" -lt "90" ]]; then
        icon="$icon_mid"
    else
        icon="$icon_full"
    fi
    echo "$icon"
}

function display_charging_bar {
    printf "%b %b %s%%" "$(get_charging_bar)" "$icon_char" "$BAT_CHARGE"
}

function display_icon {
    printf "%b %s%%" "$(get_icon)" " $BAT_CHARGE"
}

function render_unicodes {
    printf "%s" "${SEP1:-}"
    if is_charching; then
        display_charging_bar
    else
        display_icon
    fi
    printf "%s\n" "${SEP2:-}"
}

function main {
    # if not charging and low charge level critical notification
    if ! is_charching && [[ "$BAT_CHARGE" -le "$CRITICAL" ]]; then
        send_notification
    fi

    render_unicodes
}

main
