#!/usr/bin/env bash

PROG=$(basename "$0")
DEPS=(jq curl)
HUMIDITY=""
#     

# load envs
# shellcheck source=/dev/null
[[ -f "$PRIVATE_ROOT"/openweather ]] && source "$PRIVATE_ROOT"/openweather

TOKEN="$OPEN_WEATHERMAP_KEY"
CITY="$OPEN_WEATHERMAP_CITY"
UNITS="metric"
API="https://api.openweathermap.org/data/2.5"
ICONS="$SCRIPTS/icons/weather/"
GEOCLUE="https://location.services.mozilla.com/v1/geolocate?key=geoclue"

function log_err() {
	printf "%s: %s\n" "$PROG" "$@"
	notify-send -i dialog-error-symbolic "$PROG" "$@"
	exit 1
}

function get_icon() {
	case $1 in
	01d) icon="" ;;
	01n) icon="" ;;
	02d) icon="" ;;
	02n) icon="" ;;
	03*) icon="" ;;
	04*) icon="" ;;
	09*) icon="" ;;
	10d) icon="" ;;
	10n) icon="" ;;
	11d) icon="" ;;
	11n) icon="" ;;
	13*) icon="" ;;
	50*) icon="" ;;
	*) icon="" ;;
	esac

	echo "$icon "
}

function get_location() {
	local location
	location=$(curl -sf "$GEOCLUE")
	if [[ -n "$location" ]]; then
		location_lat="$(echo "$location" | jq '.location.lat')"
		location_lon="$(echo "$location" | jq '.location.lng')"
		weather=$(curl -sf "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS")
		weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
	fi
}

function get_weather() {
	# FIX: Split me...
	if [[ -n "$CITY" ]]; then

		# If is cityID
		if [[ "$CITY" -eq "$CITY" ]] 2>/dev/null; then
			city_param="id=$CITY"
		else
			city_param="q=$CITY"
		fi

		weather=$(curl -sf "$API/weather?appid=$TOKEN&$city_param&units=$UNITS")
		weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
	else
		location=$(curl -sf "$GEOCLUE")
		if [[ -n "$location" ]]; then
			location_lat="$(echo "$location" | jq '.location.lat')"
			location_lon="$(echo "$location" | jq '.location.lng')"
			weather=$(curl -sf "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS")
			weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
			echo -e "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS"
		fi
	fi
}

function notification() {
	local date icon
	date=$(date +"%a, %H:%M")
	icon="${ICONS}${2}.png"
	notify-send -i "$icon" "Weather $date" "$1"
}

function dwm_weather() {
	local icon desc temp humidity message
	get_weather
	icon=$(get_icon "$weather_icon")
	desc=$(echo "$weather" | jq -r ".weather[0].description")
	temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
	humidity=$(echo "$weather" | jq ".main.humidity" | cut -d "." -f 1)
	message="${desc} ${temp}°C ${HUMIDITY} ${humidity}%"

	printf "%s" "$SEP1"
	printf "%s" "$icon" "$message"
	printf "%s\n" "$SEP2"
	notification "$message" "$weather_icon"
}

function bar_weather() {
	local icon desc temp humidity message
	get_weather
	icon=$(get_icon "$weather_icon")
	desc=$(echo "$weather" | jq -r ".weather[0].description")
	temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
	humidity=$(echo "$weather" | jq ".main.humidity" | cut -d "." -f 1)
	message="${desc} ${temp}°C ${humidity}%"

	printf "%s" "$SEP1"
	printf "%b%s°C %b %s%%" "$icon" "$temp" "$HUMIDITY" "$humidity"
	printf "%s\n" "$SEP2"
}

for cmd in "${DEPS[@]}"; do
	if ! command -v "$cmd" >/dev/null; then
		log_err "'$cmd' command not found."
	fi
done

if ! curl -Is "${API}" >/dev/null; then
	log_err "weather API unreachable"
fi

case "$1" in
*notify) dwm_weather ;;
*) bar_weather ;;
esac
