#!/usr/bin/env bash

# bar icons
low_icon=""
mid_icon=""
high_icon=""
muted_icon=""

# notification icons
noti_low_icon="audio-volume-low-symbolic"
noti_med_icon="audio-volume-medium-symbolic"
noti_high_icon="audio-volume-high-symbolic"
noti_muted_icon="audio-volume-muted-symbolic"

notification() {
	title="$1"
	mesg="$2"
	notify-send "$title" "$mesg"
}

check_dependencies() {
	local dependencies program
	program=$(basename "$0")
	dependencies=(pamixer pulsemixer)

	for cmd in "${dependencies[@]}"; do
		if ! command -v "$cmd" >/dev/null; then
			err_msg="'$cmd' command not found."
			notification "$program script" "$err_msg"
			exit 1
		fi
	done
}

# status
current_vol=$(pamixer --get-volume)
muted_vol=$(pulsemixer --get-mute)

icon=""
noti_icon=""

dwm_pulse() {

	if [ "$muted_vol" = 1 ] || [ "$current_vol" -eq 0 ]; then
		icon="$muted_icon"
		noti_icon="$noti_muted_icon"
	elif [ "$current_vol" -gt 0 ] && [ "$current_vol" -le 23 ]; then
		icon="$low_icon"
		noti_icon="$noti_low_icon"
	elif [ "$current_vol" -gt 23 ] && [ "$current_vol" -le 66 ]; then
		icon="$mid_icon"
		noti_icon="$noti_med_icon"
	else
		icon="$high_icon"
		noti_icon="$noti_high_icon"
	fi

	printf "%s" "$SEP1"
	printf "%s %s%%" "$icon" "$current_vol"
	printf "%s\n" "$SEP2"
	dunstify -a "Volume" "Volume" "Volume: " -i "$noti_icon" -h int:value:"$current_vol" -h string:x-canonical-private-synchronous:volume
}

dwm_pulse_color() {
	local red_color="^c#ea6962^"
	local nc="^d^"

	if [ "$muted_vol" = 1 ] || [ "$current_vol" -eq 0 ]; then
		icon="${red_color}$muted_icon${nc}"
		noti_icon="$noti_muted_icon"
	elif [ "$current_vol" -gt 0 ] && [ "$current_vol" -le 23 ]; then
		icon="$low_icon"
		noti_icon="$noti_low_icon"
	elif [ "$current_vol" -gt 23 ] && [ "$current_vol" -le 66 ]; then
		icon="$mid_icon"
		noti_icon="$noti_med_icon"
	else
		icon="$high_icon"
		noti_icon="$noti_high_icon"
	fi

	printf "%s" "$SEP1"
	printf "%s %s%%" "$icon" "$current_vol"
	printf "%s\n" "$SEP2"
	dunstify -a "Volume" "Volume" "Volume: " -i "$noti_icon" -h int:value:"$current_vol" -h string:x-canonical-private-synchronous:volume
}

main() {
	check_dependencies
	if [ "$DWM_COLOR" = true ]; then
		dwm_pulse_color
	else
		dwm_pulse
	fi
}

main
