#!/usr/bin/env bash

PROG=$(basename "$0")
CURRENT_VOL=$(pamixer --get-volume)
DEPS=(pamixer pulsemixer)
ICON_BAR=""
ICON_NOTIFY=""

# bar icons
#     
low_icon=""
mid_icon=""
high_icon=""
muted_icon=""

# notification icons
noti_low_icon="audio-volume-low-symbolic"
noti_med_icon="audio-volume-medium-symbolic"
noti_high_icon="audio-volume-high-symbolic"
noti_over_icon="audio-volume-overamplified-symbolic"
noti_muted_icon="audio-volume-muted-symbolic"

check_dependencies() {
	local cmd err_msg
	for cmd in "${DEPS[@]}"; do
		if ! command -v "$cmd" >/dev/null; then
			err_msg="'$cmd' command not found."
			notify-send "$PROG" "$err_msg"
			exit 1
		fi
	done
}

function get_icons() {
	if is_muted || [[ "$CURRENT_VOL" -eq 0 ]]; then
		ICON_BAR="$muted_icon"
		ICON_NOTIFY="$noti_muted_icon"
	elif [[ "$CURRENT_VOL" -gt 0 && "$CURRENT_VOL" -le 15 ]]; then
		ICON_BAR="$low_icon"
		ICON_NOTIFY="$noti_low_icon"
	elif [[ "$CURRENT_VOL" -gt 15 && "$CURRENT_VOL" -le 66 ]]; then
		ICON_BAR="$mid_icon"
		ICON_NOTIFY="$noti_med_icon"
	elif [[ "$CURRENT_VOL" -gt 66 && "$CURRENT_VOL" -le 100 ]]; then
		ICON_BAR="$high_icon"
		ICON_NOTIFY="$noti_high_icon"
	else
		ICON_BAR="$high_icon"
		ICON_NOTIFY="$noti_over_icon"
	fi
}

function is_muted() {
	local muted
	muted=$(pulsemixer --get-mute)

	if [[ "${muted}" -ne 1 ]]; then
		return 1
	fi

	return 0
}

function notify-vol() {
	local icon="$1"
	local appname="Volume"
	local hints="string:x-canonical-private-synchronous:volume"
	dunstify -a "$appname" "$appname" "$appname: " -i "$icon" -h int:value:"$CURRENT_VOL" -h "${hints}"
}

function main() {
	check_dependencies
	get_icons

	printf "%s" "$SEP1"
	printf "%s  %s%%" "$ICON_BAR" "$CURRENT_VOL"
	printf "%s\n" "$SEP2"

	notify-vol "$ICON_NOTIFY"
}

main
