#!/usr/bin/env bash

# Script for displaying battery status in dwm bar.
#
# Output: [UNICODE 98%]
# Output: [UNICODE 98% status]

BAT_CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
CRITICAL=10

# notification icons
warn="🔴"
if [[ "${DWM_BAR_FILLED:-1}" -eq 0 ]]; then
    icon_critical=" "
    icon_empty=" "
    icon_low=" "
    icon_mid=" "
    icon_full=" "
    icon_char=""
else
    icon_critical="󰂎"
    icon_empty="󰁺"
    icon_low="󰁼"
    icon_mid="󰁿"
    icon_full="󰁹"
    icon_char=""
fi

case "${BLOCK_BUTTON:-}" in
3) notify-send "🔋 Battery module" "🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
${icon_char}: charged
❗: battery very low!
- Scroll to change adjust xbacklight." ;;
4) xbacklight -inc 10 ;;
5) xbacklight -dec 10 ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
*) ;;
esac

function _notifyme {
    local args
    local cmd=notify-send
    declare -a args=(-a "Battery" "Battery" "Battery critical: ")
    args+=(-r 999 --urgency=critical)
    args+=(-i "battery-level-10-symbolic")
    args+=(-h int:value:"$BAT_CHARGE")
    args+=(-h string:x-canonical-private-synchronous:battery)
    "$cmd" "${args[@]}"
}

function _bat_statues {
    local current
    current=$(cat /sys/class/power_supply/BAT0/status)
    echo "$current"
}

function _is_charching {
    if [[ $(_bat_statues) != "Charging" ]]; then
        return 1
    fi
    return 0
}

function _get_charging_bar_short {
    local start=""
    local full=""
    local empty=""
    local end_empty=""
    # local end_full="" # <-
    local charge_level icon
    charge_level=$((BAT_CHARGE / 10))
    icon="${start}$(printf '%s%.0s' "${full}" $(seq 1 "$charge_level"))$(printf '%s%.0s' "${empty}" $(seq "$charge_level" 8))${end_empty}"
    echo "$icon"
}

function _get_charging_bar_other {
    local bars=("" "▏" "▎" "▍" "▌" "▋" "▊" "▉" "█")
    local index=$((BAT_CHARGE * 8 / 100))
    echo "[${bars[index]}${BAT_CHARGE}%]"
}

function _get_charging_bar {
    # Output: [  50%]
    #  
    # ▓ ▒ ░
    local icon_start=""
    local icon_full=""
    local icon_empty=""
    local icon_end_empty=""
    local icon_end_full=""
    local icon="$icon_start"

    local charge_level
    charge_level=$((BAT_CHARGE / 10))

    for i in $(seq 2 9); do
        if [[ $i -le $charge_level ]]; then
            icon+="$icon_full"
        else
            icon+="$icon_empty"
        fi
    done

    if [[ $charge_level -ge 10 ]]; then
        icon+="$icon_end_full"
    else
        icon+="$icon_end_empty"
    fi

    echo "$icon"
}

function _get_icon {
    local icon=""
    if [[ "$BAT_CHARGE" -lt "20" ]]; then
        icon="$warn $icon_critical"
    elif [[ "$BAT_CHARGE" -lt "30" ]]; then
        icon="$icon_empty"
    elif [[ "$BAT_CHARGE" -lt "50" ]]; then
        icon="$icon_low"
    elif [[ "$BAT_CHARGE" -lt "90" ]]; then
        icon="$icon_mid"
    else
        icon="$icon_full"
    fi
    echo "$icon"
}

function _display_charging_bar {
    printf "%b %b %s%%" "$(_get_charging_bar)" "$icon_char" "$BAT_CHARGE"
}

function _display_icon {
    printf "%b%s%%" "$(_get_icon)" " $BAT_CHARGE"
}

function _render_unicodes {
    printf "%s" "${SEP1:-}"
    if _is_charching; then
        _display_charging_bar
    else
        _display_icon
    fi
    printf "%s\n" "${SEP2:-}"
}

function main {
    # if not charging and low charge level critical notification
    if ! _is_charching && [[ "$BAT_CHARGE" -le "$CRITICAL" ]]; then
        _notifyme
    fi

    _render_unicodes
    # _display_icon
}

main
