#!/usr/bin/env bash

# Script for displaying pomodoro status in dwm bar.
#
# Output: [ICON time]

PROG="${0##*/}"
CMD=timer

if ! command -v "$CMD" >/dev/null; then
    printf "%s: %s\n" "$PROG" "err: $CMD not found"
    exit 1
fi

status=$($CMD status)
[[ -z "$status" ]] && exit

if [[ "${DWM_BAR_FILLED:-1}" -eq 0 ]]; then
    ICON=""
else
    ICON=""
fi

echo "$ICON $($CMD status)"
