#!/bin/sh

# ╺┳┓┏━┓╺┳╸┏━╸
#  ┃┃┣━┫ ┃ ┣╸
# ╺┻┛╹ ╹ ╹ ┗━╸
# formatted date.
#
# output: "[ICON Fri, DD MMM]"
#      
ICON=" "

# fmt_date="$(date "+%a %d-%m")"

printf "%s%s %s%s\n" "${SEP:-}" "$ICON" "$(date "+%a %d %b")" "${SEP:-}"
