#!/usr/bin/env bash

# Script for displaying pomodoro status in dwm bar.
#
# Output: [ICON time]

PROG=$(basename "$0")
CMD="alarm"

if ! command -v "$CMD" >/dev/null; then
    printf "%s: %s\n" "$PROG" "$CMD not found"
    exit 1
fi

$CMD status
