#!/usr/bin/env bash

# Script for displaying network usage in dwm bar.
#
# Output: [ICON_DOWN  1.6MB ICON_UP  24KB]
#                      

monitors=$(xrandr --query | grep -w 'connected' | awk '{print $1;}' | wc -l)
if [[ "$monitors" -eq 1 ]]; then
    exit
fi

case "${BLOCK_BUTTON:-}" in
1) setsid -f "${TERMINAL:-st}" -e bmon ;;
3) notify-send "🌐 Network traffic module" "🔻: Traffic received
🔺: Traffic transmitted" ;;
6) setsid -f "${TERMINAL:-st}" -e "${EDITOR:-nvim}" "$0" ;;
*) ;;
esac

if [[ "${DWM_BAR_FILLED:-1}" -eq 0 ]]; then
    icon_up=""
    icon_down=""
else
    icon_up=""
    icon_down=""
fi

function update {
    sum=0
    for arg; do
        read -r i <"$arg"
        sum=$((sum + i))
    done
    cache=/tmp/${1##*/}
    [[ -f "$cache" ]] && read -r old <"$cache" || old=0
    printf %d\\n "$sum" >"$cache"
    printf %d\\n $((sum - old))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

printf "${SEP1:-}%s  %4sB %s  %4sB${SEP2:-}\\n" "$icon_down" "$(numfmt --to=iec "$rx")" "$icon_up" "$(numfmt --to=iec "$tx")"
