#!/usr/bin/env bash

# Script for displaying pomodoro status in dwm bar.
#
# Output: [ICON time]

PROG="${0##*/}"
CMD=timer

if ! command -v "$CMD" >/dev/null; then
    printf "%s: %s\n" "$PROG" "err: $CMD not found"
    exit 1
fi

$CMD status
