#!/usr/bin/env bash

# Script for displaying network usage in dwm bar.
#
# Output: [ICON_DOWN  1.6MB ICON_UP  24KB]
#                      
icon_up=""
icon_down=""

function update {
    sum=0
    for arg; do
        read -r i <"$arg"
        sum=$((sum + i))
    done
    cache=/tmp/${1##*/}
    [[ -f "$cache" ]] && read -r old <"$cache" || old=0
    printf %d\\n "$sum" >"$cache"
    printf %d\\n $((sum - old))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

printf "${SEP1:-}%s  %4sB %s  %4sB${SEP2:-}\\n" "$icon_down" "$(numfmt --to=iec "$rx")" "$icon_up" "$(numfmt --to=iec "$tx")"
