#!/usr/bin/env bash

# Script for displaying current time in dwm bar.
#
# Output: [ICON 16:12]

if [[ "${DWM_BAR_FILLED:-1}" -eq 0 ]]; then
    icon=""
else
    icon=" "
fi
printf "%s%s %s%s\n" "${SEP1:-}" "$icon" "$(date "+%H:%M")" "${SEP2:-}"
