#!/usr/bin/env bash

# Script for displaying current CPU governor in dwm bar.
#
# Output: [ICON governor]

icon=""
governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)

printf "%s%b %s%s\n" "${SEP1:-}" "$icon" "$governor" "${SEP2:-}"
