#!/usr/bin/env bash

# script for displaying transmission status
#
# output:
#  15  3  1  1  1  1

set -o pipefail

function main {
    if ! pgrep -f "transmission-daemon" >/dev/null; then
        return
    fi

    transmission-remote -l | grep % |
        sed " # The letters are for sorting and will not appear.
    s/.*Stopped.*/A  /;
    s/.*Seeding.*/Z  /;
    s/.*100%.*/N  /;
    s/.*Idle.*/B  /;
    s/.*Uploading.*/L  /;
    s/.*%.*/M  /" |
        sort -h | uniq -c | awk '{print $3, $1}' | paste -sd '  ' -
}

main
