#!/bin/sh

# ╺┳┓┏━┓╺┳╸┏━╸
#  ┃┃┣━┫ ┃ ┣╸
# ╺┻┛╹ ╹ ╹ ┗━╸
# formatted date.
#
# output: "[ICON Fri, DD MMM]"
#      

ICON=" "
monitors=$(xrandr --query | grep -w 'connected' | awk '{print $1;}' | wc -l)
if [ "$monitors" -eq 1 ]; then
    d=$(date "+%d %b")
else
    d=$(date "+%a %d %b")
fi

printf "%s%s %s%s\n" "${SEP:-}" "$ICON" "$d" "${SEP:-}"
