#!/bin/sh

# Output: "[ICON Fri DD-MM]"
#   
icon=""

date_var=$(date "+%a %d-%m")

dwm_date_color() {
	blue="^c#83a598^"
	reset="^d^"
	printf "%s" "$SEP1"
	printf "%s%s %s%s" "$blue" "$icon" "$date_var" "$reset"
	printf "%s\n" "$SEP2"
}

dwm_date() {
	printf "%s" "$SEP1"
	printf "%s %s" "$icon" "$date_var"
	printf "%s\n" "$SEP2"
}

if [ "$DWM_COLOR" = true ]; then
	dwm_date_color
else
	dwm_date
fi
