#!/usr/bin/env bash

PROG=$(basename "$0")
LAYOUT="us"
DEPS=(setxkbmap xset)
VARIANT="altgr-intl"
SETXKB=/usr/bin/setxkbmap
ICON=""

logme() {
	printf "%s: %s\n" "$PROG" "$1"
}

log_exit() {
	printf "%s: %s\n" "$PROG" "$1" >&2
	exit 1
}

set_rules() {
	local retcode

	$SETXKB -rules evdev \
		-model evdev \
		-layout "${LAYOUT}" \
		-variant "${VARIANT}" \
		-option caps:swapescape \
		-option compose:ralt

	retcode=$?
	if [[ $retcode -ne 0 ]]; then
		log_exit "setxkbmap failed"
	fi

	xset r rate 200 50
	# xset r rate 300 50
	# xset r rate 250 44
}

get_xkbmap() {
	local current
	current=$($SETXKB -query | grep "layout\|variant" | awk '{print $2}' | paste -sd "_")
	echo "$current"
}

bar_output() {
	local current
	current=$(get_xkbmap)
	printf "%b %s" "$ICON" "$current"
}

main() {
	for dep in "${DEPS[@]}"; do
		if ! command -v "${dep}" >/dev/null; then
			log_exit "'${dep}' not found"
		fi
	done

	if [[ "$(get_xkbmap)" == "${LAYOUT}_$VARIANT" ]]; then
		log_exit "already in layout='${LAYOUT}' variant='$VARIANT'"
	fi

	logme "setting -> ${LAYOUT}_$VARIANT"
	set_rules

	exit 0
}

main "$@"
